# Staging environment overrides

replicaCount: 2

image:
  repository: 435073375959.dkr.ecr.ap-south-1.amazonaws.com/movie-watchlist
  tag: "latest"
  pullPolicy: IfNotPresent

app:
  env: staging

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4