apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "movie-watchlist.fullname" . }}
  labels:
    {{- include "movie-watchlist.labels" . | nindent 4 }}
data:
  mongodb-host: "{{ .Values.mongodb.host }}"
  mongodb-port: "{{ .Values.mongodb.port }}"