apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "movie-watchlist.fullname" . }}
  labels:
    {{- include "movie-watchlist.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "movie-watchlist.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s